#spring.jpa.database=MYSQL
## Show or not log for each sql query
##spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-test?useUnicode=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update